CREATE TABLE IF NOT EXISTS delegates (
  Name VARCHAR(150),
  School VARCHAR(150),
  Age INT,
  MUNs INT,
  Committee VARCHAR(50),
  Portfolio_1 VARCHAR(150),
  Portfolio_2 VARCHAR(150),
  BD INT,
  HC INT,
  SM INT,
  HM INT,
  VM INT
);

INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Wahab Khalsa', 'Delhi Public School', 15, 5, 'UNHRC', 'Russia', 'Germany', 0, 1, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Aahana Dixit', 'DAV Gopalapuram', 14, 1, 'AIPPM', 'Naveen Patnaik', 'Nitish Kumar', 0, 0, 2, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zayan Khanna', 'Chinmaya Vidyalaya', 17, 2, 'CRISIS', 'Australia', 'France', 0, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ekapad Lad', 'Velammal Vidyalaya', 16, 4, 'UNHRC', 'Germany', 'USA', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Urmi Tata', 'Chettinad Vidyashram', 15, 2, 'UNGA', 'Japan', 'Russia', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Kanda', 'National Public School', 14, 0, 'UNHRC', 'UK', 'India', 0, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ati Chaudhuri', 'SBOA School & Jr. College', 17, 7, 'AIPPM', 'Uddhav Thackeray', 'Asaduddin Owaisi', 1, 1, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Utkarsh Bail', 'PSBB', 16, 3, 'CRISIS', 'France', 'Germany', 0, 1, 0, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Lipika Maharaj', 'Hindustan Intl School', 15, 2, 'UNGA', 'China', 'USA', 2, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bakhshi Nagarajan', 'The Pupil Saveetha', 14, 5, 'AIPPM', 'P. Chidambaram', 'Narendra Modi', 0, 1, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Arya Sami', 'DAV Gopalapuram', 17, 8, 'UNHRC', 'India', 'Brazil', 0, 0, 1, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Tristan Balasubramanian', 'PSBB', 15, 1, 'CRISIS', 'Japan', 'Russia', 1, 0, 0, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yasti Shroff', 'Chettinad Vidyashram', 16, 3, 'UNGA', 'USA', 'France', 0, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zehaan Edwin', 'Chinmaya Vidyalaya', 14, 0, 'UNHRC', 'Germany', 'Australia', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Sathvik Ravel', 'Hindustan Intl School', 17, 6, 'AIPPM', 'Amit Shah', 'Nirmala Sitharaman', 2, 1, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Kalpit Gade', 'Velammal Vidyalaya', 15, 2, 'UNGA', 'UK', 'Brazil', 1, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Aadhya Warrior', 'National Public School', 14, 4, 'UNHRC', 'Russia', 'Japan', 0, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Patrick Lad', 'SBOA School & Jr. College', 16, 3, 'CRISIS', 'Australia', 'France', 0, 2, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Faraj Kamdar', 'DAV Gopalapuram', 15, 1, 'UNGA', 'China', 'India', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Kai Shah', 'PSBB', 17, 5, 'AIPPM', 'Sonia Gandhi', 'Tejasvi Surya', 0, 0, 2, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Mohini Bera', 'Chettinad Vidyashram', 14, 6, 'UNHRC', 'Brazil', 'USA', 1, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Anirudh Bobal', 'Chinmaya Vidyalaya', 15, 2, 'CRISIS', 'France', 'Japan', 0, 0, 1, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Nimrat Dash', 'Delhi Public School', 16, 0, 'UNGA', 'Russia', 'India', 0, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Riya Soni', 'Hindustan Intl School', 14, 7, 'AIPPM', 'Asaduddin Owaisi', 'Chandra Babu Naidu', 2, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Janya Keer', 'The Pupil Saveetha', 15, 3, 'CRISIS', 'Germany', 'USA', 1, 0, 0, 1, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ikshita Bir', 'SBOA School & Jr. College', 16, 2, 'UNGA', 'UK', 'India', 0, 1, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ranbir Gulati', 'PSBB', 17, 4, 'AIPPM', 'Uddhav Thackeray', 'Yogi Adityanath', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Damini Balakrishnan', 'DAV Gopalapuram', 14, 6, 'UNHRC', 'France', 'Brazil', 2, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Jeremiah Ganguly', 'Chinmaya Vidyalaya', 15, 0, 'UNGA', 'Australia', 'Germany', 0, 2, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Finn Chokshi', 'National Public School', 16, 1, 'AIPPM', 'Biren Singh', 'Bhupender Yadav', 1, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Mahika Luthra', 'Hindustan Intl School', 14, 3, 'CRISIS', 'USA', 'Russia', 0, 0, 0, 2, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Chameli Mitter', 'Chettinad Vidyashram', 17, 5, 'UNHRC', 'Japan', 'Brazil', 0, 1, 2, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zayan Khanna', 'Chinmaya Vidyalaya', 15, 2, 'UNGA', 'India', 'UK', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ekapad Lad', 'PSBB', 14, 1, 'AIPPM', 'Mansukh Mandaviya', 'Biren Singh', 0, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Udarsh Sastry', 'DAV Gopalapuram', 16, 3, 'CRISIS', 'China', 'USA', 2, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Triya Chacko', 'Velammal Vidyalaya', 15, 7, 'UNGA', 'Brazil', 'India', 0, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Tristan Balasubramanian', 'The Pupil Saveetha', 14, 5, 'UNHRC', 'Russia', 'Australia', 1, 2, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Xalak Devan', 'SBOA School & Jr. College', 16, 4, 'AIPPM', 'Piyush Goyal', 'Kanimozhi Karunanidhi', 0, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Kanda', 'National Public School', 15, 6, 'CRISIS', 'USA', 'China', 0, 1, 0, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Parekh', 'PSBB', 17, 2, 'UNGA', 'Brazil', 'India', 1, 0, 0, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Atharv Rai', 'DAV Gopalapuram', 14, 3, 'UNHRC', 'France', 'Japan', 0, 0, 1, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Wahab Khalsa', 'Hindustan Intl School', 16, 4, 'AIPPM', 'Eknath Shinde', 'Amit Shah', 2, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Urvashi Mohan', 'Chinmaya Vidyalaya', 15, 0, 'CRISIS', 'Australia', 'USA', 1, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Charles Dugar', 'Chettinad Vidyashram', 14, 2, 'UNGA', 'Japan', 'France', 0, 2, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Abhimanyu Khatri', 'The Pupil Saveetha', 17, 5, 'UNHRC', 'India', 'Germany', 0, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Anirudh Bobal', 'National Public School', 16, 3, 'AIPPM', 'Mallikarjun Kharge', 'Nitish Kumar', 1, 1, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Ahluwalia', 'SBOA School & Jr. College', 15, 1, 'CRISIS', 'Russia', 'China', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Rishi Edwin', 'Chinmaya Vidyalaya', 14, 6, 'UNGA', 'Australia', 'India', 1, 0, 0, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Harshil Bobal', 'PSBB', 17, 2, 'UNHRC', 'Germany', 'USA', 0, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Andrew Malhotra', 'Chettinad Vidyashram', 15, 4, 'UNGA', 'UK', 'Russia', 0, 1, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yachana Gandhi', 'Chinmaya Vidyalaya', 16, 2, 'AIPPM', 'Nitish Kumar', 'Arvind Kejriwal', 1, 0, 0, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Triya Chacko', 'DAV Gopalapuram', 14, 6, 'CRISIS', 'Brazil', 'USA', 0, 0, 2, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Parekh', 'PSBB', 15, 3, 'UNHRC', 'Japan', 'France', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ishani Khanna', 'The Pupil Saveetha', 17, 0, 'UNGA', 'Australia', 'Germany', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Patrick Lad', 'SBOA School & Jr. College', 16, 1, 'AIPPM', 'Amit Shah', 'Mansukh Mandaviya', 0, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Rishi Edwin', 'Hindustan Intl School', 14, 7, 'CRISIS', 'France', 'China', 2, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Udarsh Borde', 'Delhi Public School', 17, 5, 'UNGA', 'Russia', 'Brazil', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Divya Sen', 'Velammal Vidyalaya', 16, 4, 'UNHRC', 'Germany', 'USA', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Geetika Zachariah', 'Chinmaya Vidyalaya', 15, 3, 'AIPPM', 'Jitendra Singh', 'Nitin Gadkari', 1, 0, 0, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ikshita Bir', 'PSBB', 14, 6, 'CRISIS', 'India', 'China', 1, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Janya Keer', 'DAV Gopalapuram', 15, 2, 'UNGA', 'France', 'Australia', 0, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Abhimanyu Khatri', 'The Pupil Saveetha', 16, 5, 'UNHRC', 'Germany', 'Brazil', 0, 1, 0, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ati Chaudhuri', 'SBOA School & Jr. College', 15, 1, 'AIPPM', 'Asaduddin Owaisi', 'Amit Shah', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavika Gole', 'Chinmaya Vidyalaya', 14, 3, 'CRISIS', 'USA', 'Japan', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Odika Nayar', 'National Public School', 17, 2, 'UNGA', 'Russia', 'Australia', 0, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ojas Sarma', 'PSBB', 15, 7, 'UNHRC', 'Germany', 'Brazil', 2, 1, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Pushti Gour', 'DAV Gopalapuram', 16, 3, 'AIPPM', 'Nitish Kumar', 'Priyanka Gandhi', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Advay Vyas', 'Chettinad Vidyashram', 14, 6, 'CRISIS', 'Japan', 'China', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Jackson Nagarajan', 'Chinmaya Vidyalaya', 15, 4, 'UNGA', 'India', 'USA', 1, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Qarin Zachariah', 'Hindustan Intl School', 17, 1, 'UNHRC', 'Russia', 'Australia', 0, 2, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zehaan Edwin', 'SBOA School & Jr. College', 16, 5, 'AIPPM', 'Asaduddin Owaisi', 'Bhupender Yadav', 0, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Falguni Sodhi', 'PSBB', 14, 0, 'CRISIS', 'Germany', 'Japan', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashvi Sule', 'The Pupil Saveetha', 15, 6, 'UNGA', 'UK', 'China', 2, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Dayamai Aggarwal', 'Chettinad Vidyashram', 16, 2, 'UNHRC', 'India', 'France', 1, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Kanda', 'DAV Gopalapuram', 15, 4, 'AIPPM', 'Rajnath Singh', 'Sharad Pawar', 0, 0, 1, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Oni Saini', 'PSBB', 14, 2, 'CRISIS', 'Germany', 'Brazil', 1, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Amol Ganesan', 'Chinmaya Vidyalaya', 17, 3, 'UNGA', 'China', 'Japan', 0, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashvi Lad', 'Hindustan Intl School', 15, 6, 'UNHRC', 'India', 'Australia', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Faraj Kamdar', 'SBOA School & Jr. College', 16, 1, 'AIPPM', 'Udhayanidhi Stalin', 'Piyush Goyal', 2, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yasti Shroff', 'The Pupil Saveetha', 14, 5, 'CRISIS', 'UK', 'India', 0, 1, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Divya Sen', 'PSBB', 15, 2, 'UNGA', 'Brazil', 'Germany', 0, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Faraj Wagle', 'Delhi Public School', 16, 4, 'UNHRC', 'Japan', 'UK', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ekalinga Bhargava', 'Velammal Vidyalaya', 17, 0, 'AIPPM', 'Udhayanidhi Stalin', 'Dharmendra Pradhan', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yasti Bora', 'Chettinad Vidyashram', 14, 3, 'CRISIS', 'India', 'Brazil', 0, 1, 0, 2, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Chameli Mitter', 'Chinmaya Vidyalaya', 15, 5, 'UNGA', 'Germany', 'Japan', 0, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Deepa Ganesh', 'DAV Gopalapuram', 16, 2, 'UNHRC', 'France', 'China', 1, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Vidhi Ratta', 'National Public School', 14, 6, 'AIPPM', 'Eknath Shinde', 'Seeman', 0, 2, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ekapad Lad', 'SBOA School & Jr. College', 15, 1, 'CRISIS', 'Brazil', 'Australia', 1, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zayan Khanna', 'Hindustan Intl School', 17, 4, 'UNGA', 'India', 'France', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Rushil Tandon', 'PSBB', 14, 5, 'UNHRC', 'Russia', 'USA', 0, 0, 2, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Eiravati Mahajan', 'The Pupil Saveetha', 15, 3, 'AIPPM', 'Priyanka Gandhi', 'Thirumavalavan', 2, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Viraj Khalsa', 'Chettinad Vidyashram', 16, 2, 'CRISIS', 'Germany', 'India', 1, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ikshita Bir', 'DAV Gopalapuram', 17, 4, 'UNGA', 'Japan', 'Brazil', 0, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Ahluwalia', 'Chinmaya Vidyalaya', 15, 0, 'UNHRC', 'UK', 'Australia', 1, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ranbir Gulati', 'Velammal Vidyalaya', 14, 3, 'AIPPM', 'Rahul Gandhi', 'Dharmendra Pradhan', 1, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Jackson Nagarajan', 'National Public School', 16, 1, 'CRISIS', 'China', 'Russia', 0, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Hritik Bhatia', 'Hindustan Intl School', 15, 5, 'UNGA', 'India', 'Brazil', 0, 0, 0, 2, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Mohini Bera', 'SBOA School & Jr. College', 17, 6, 'UNHRC', 'Germany', 'Japan', 2, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Sathvik Ravel', 'PSBB', 14, 2, 'AIPPM', 'Jitendra Singh', 'Thirumavalavan', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Riya Soni', 'DAV Gopalapuram', 15, 3, 'CRISIS', 'Brazil', 'India', 0, 0, 1, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Eesha Chaudry', 'Chinmaya Vidyalaya', 17, 2, 'UNGA', 'Japan', 'Germany', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashoda Bava', 'The Pupil Saveetha', 14, 6, 'UNHRC', 'China', 'Australia', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashvi Lad', 'SBOA School & Jr. College', 15, 5, 'AIPPM', 'Sharad Pawar', 'Biren Singh', 2, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Harshil Bobal', 'PSBB', 16, 4, 'CRISIS', 'USA', 'Russia', 1, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Adweta Tak', 'Chettinad Vidyashram', 14, 1, 'UNGA', 'India', 'Japan', 0, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Oni Saini', 'Hindustan Intl School', 15, 6, 'UNHRC', 'Brazil', 'Germany', 0, 2, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashvi Sule', 'DAV Gopalapuram', 17, 0, 'AIPPM', 'Kanimozhi Karunanidhi', 'Revanth Reddy', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Triya Chacko', 'Chinmaya Vidyalaya', 16, 3, 'CRISIS', 'China', 'India', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Mahika Luthra', 'PSBB', 15, 2, 'UNGA', 'USA', 'Australia', 0, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Gavin Thaman', 'National Public School', 14, 5, 'UNHRC', 'Russia', 'Germany', 0, 0, 2, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Pushti Gour', 'SBOA School & Jr. College', 17, 4, 'AIPPM', 'Dharmendra Pradhan', 'Biren Singh', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Zehaan Edwin', 'Hindustan Intl School', 15, 1, 'CRISIS', 'France', 'China', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ati Chaudhuri', 'The Pupil Saveetha', 14, 3, 'UNGA', 'India', 'Brazil', 2, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Deepa Ganesh', 'Chinmaya Vidyalaya', 16, 2, 'UNHRC', 'USA', 'Germany', 0, 1, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Manya Pillay', 'Chettinad Vidyashram', 15, 4, 'AIPPM', 'Eknath Shinde', 'Vijay', 1, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Andrew Malhotra', 'PSBB', 14, 3, 'CRISIS', 'France', 'India', 0, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Charles Dugar', 'DAV Gopalapuram', 17, 2, 'UNGA', 'Brazil', 'Japan', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ojas Sarma', 'Hindustan Intl School', 16, 0, 'UNHRC', 'China', 'Australia', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Amol Ganesan', 'SBOA School & Jr. College', 15, 5, 'AIPPM', 'Arjun Munda', 'Sonia Gandhi', 2, 0, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Udarsh Borde', 'PSBB', 14, 1, 'CRISIS', 'UK', 'Russia', 0, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Damini Balakrishnan', 'Chinmaya Vidyalaya', 17, 4, 'UNGA', 'India', 'USA', 1, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Jairaj Chowdhury', 'Chettinad Vidyashram', 16, 2, 'UNHRC', 'Japan', 'Brazil', 0, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Arya Sami', 'The Pupil Saveetha', 15, 5, 'AIPPM', 'Mamata Banerjee', 'Sonia Gandhi', 1, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Fitan Maharaj', 'DAV Gopalapuram', 14, 6, 'CRISIS', 'France', 'Australia', 0, 0, 2, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bakhshi Nagarajan', 'PSBB', 16, 2, 'UNGA', 'Germany', 'China', 0, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Wishi Kamdar', 'Chinmaya Vidyalaya', 15, 3, 'UNHRC', 'India', 'USA', 1, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Eesha Chaudry', 'DAV Gopalapuram', 14, 5, 'AIPPM', 'Nitin Gadkari', 'Jitendra Singh', 0, 2, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Atharv Rai', 'The Pupil Saveetha', 17, 4, 'CRISIS', 'France', 'Australia', 1, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Oni Saini', 'SBOA School & Jr. College', 16, 1, 'UNGA', 'UK', 'Japan', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Udarsh Sastry', 'National Public School', 15, 6, 'UNHRC', 'Russia', 'Germany', 0, 0, 1, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Abhimanyu Khatri', 'Hindustan Intl School', 14, 3, 'AIPPM', 'Mamata Banerjee', 'Biren Singh', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Rishi Edwin', 'PSBB', 17, 2, 'CRISIS', 'India', 'UK', 0, 1, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Aahana Dixit', 'DAV Gopalapuram', 15, 0, 'UNGA', 'Germany', 'USA', 0, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Chameli Mitter', 'Chettinad Vidyashram', 14, 1, 'UNHRC', 'France', 'Australia', 1, 0, 0, 0, 2);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Udarsh Borde', 'Chinmaya Vidyalaya', 16, 5, 'AIPPM', 'S. Jaishankar', 'Lalduhoma', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Triya Chacko', 'SBOA School & Jr. College', 15, 2, 'CRISIS', 'Brazil', 'India', 2, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Andrew Malhotra', 'The Pupil Saveetha', 14, 4, 'UNGA', 'UK', 'France', 1, 0, 1, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yashvi Lad', 'Chinmaya Vidyalaya', 17, 2, 'UNHRC', 'USA', 'China', 0, 1, 0, 0, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Xalak Devan', 'National Public School', 15, 3, 'AIPPM', 'Tejasvi Surya', 'Jitendra Singh', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Dayita Gaba', 'Chettinad Vidyashram', 14, 6, 'CRISIS', 'France', 'UK', 1, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Yasti Bora', 'DAV Gopalapuram', 16, 3, 'UNGA', 'Russia', 'Brazil', 0, 0, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Urmi Tata', 'PSBB', 15, 4, 'UNHRC', 'China', 'Japan', 1, 1, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Geetika Zachariah', 'Hindustan Intl School', 14, 0, 'AIPPM', 'Seeman', 'Kanimozhi Karunanidhi', 0, 0, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Harshil Bobal', 'SBOA School & Jr. College', 17, 2, 'CRISIS', 'Brazil', 'France', 0, 0, 0, 2, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Tristan Balasubramanian', 'The Pupil Saveetha', 15, 6, 'UNGA', 'UK', 'Germany', 0, 1, 1, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Bhavini Kanda', 'Chinmaya Vidyalaya', 16, 3, 'UNHRC', 'Australia', 'China', 1, 0, 0, 1, 1);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ekalinga Bhargava', 'DAV Gopalapuram', 14, 5, 'AIPPM', 'Piyush Goyal', 'Udhayanidhi Stalin', 0, 2, 0, 0, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Ojas Sarma', 'PSBB', 17, 4, 'CRISIS', 'USA', 'Russia', 1, 0, 0, 1, 0);
INSERT INTO delegates (Name, School, Age, MUNs, Committee, Portfolio_1, Portfolio_2, BD, HC, SM, HM, VM) VALUES ('Gavin Thaman', 'Chinmaya Vidyalaya', 15, 1, 'UNGA', 'Germany', 'India', 0, 0, 0, 0, 2);